import canonicalLaneMathlib.AdmissibleClass

namespace HautevilleHouse
namespace EarthScienceGeohazardsTheoremCanonicalLaneLean

end EarthScienceGeohazardsTheoremCanonicalLaneLean
end HautevilleHouse
